# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * 0"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: foursixnine
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit,pull_request,issue
          plugin_notable_self: yes
          plugin_notable_indepth: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, lex, gnuplot, robotframework, scss, jinja, renderscript
          plugin_languages_aliases: raku:perl
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 5
          plugin_languages_recent_days: 360
          plugin_languages_analysis_timeout: 120
          plugin_languages_sections: most-used, recently-used
          plugin_habits: yes
          plugin_habits_days: 180
          plugin_habits_facts: yes
          plugin_habits_from: 180
          plugin_habits_languages_limit: 5
          plugin_habits_languages_threshold: 20%
          plugin_habits_skipped: 
            foursixnine/foursixnine
          plugin_lines: yes
          plugin_lines_history_limit: 2
          plugin_lines_repositories_limit: 4
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: D
